url: https://asvoria.github.io
baseurl: /olmcf/

# Site settings
title: Ong Lai Mun Charity Fund
email: asvoria@live.com
description: "This site is a public record of the Ong Lai Mun Charity Fund"


# Team names, titles and social links
people:
- name: SEED
  pic: seed
  position: Description
  social:
    - title: globe
      url: https://seedfoundation.com.my/
    - title: facebook
      url: https://www.facebook.com/SEEDFMalaysia/

- name: One Hope Charity
  pic: one_hope
  position: Description
  social:
    - title: globe
      url: http://www.onehopecharity.org/
    - title: facebook
      url: https://www.facebook.com/onehopecharitywelfare/

- name: Special Hands
  pic: special_hands
  position: Description
  social:
    - title: globe
      url: http://www.asiacommunityservice.org/
    - title: facebook
      url: https://www.facebook.com/acs.specialhands

- name: Binance Charity
  pic: binance_cha
  position: Description
  social:
    - title: globe
      url: https://www.binance.charity/
    - title: facebook
      url: https://www.facebook.com/BinanceBCF/
    - title: twitter
      url: https://twitter.com/BinanceBCF

- name: Give.Asia
  pic: giveasia
  position: Description
  social:
    - title: globe
      url: https://give.asia/
    - title: facebook
      url: https://www.facebook.com/giveasia.org/

- name: BEH SWEE CHENG
  pic: Yellow_Tulips_by_Kailanie
  position: Description

- name: CHUN YIN LING
  pic: chunyinling
  position: Description

- name: MAH LAI MUN
  pic: mahlaimun
  position: Description

- name: MD. TAYUB ABU TALEK
  pic: balukhali
  position: Tayub is a Rohingyan reside in Malaysia, where his family relatives stays at Balukhali Camp. In March 2021, a fire struck the camp. The fund is collected and delivered to Tayub's relatives at Balukhali to rebuild their camps.  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/olmcf/

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-cayman
