url: https://asvoria.github.io
baseurl: /olmcf/

# Site settings
title: Ong Lai Mun Charity Fund
email: asvoria@live.com
description: "This site is a public record of the Ong Lai Mun Charity Fund"


# Team names, titles and social links
people:
- name: SEED
  pic: 1
  social:
    - title: webpage
      url: https://www.youtube.com/channel/UCUbr-n1cvqLvmmnKmA8JWzA
    - title: facebook
      url: https://www.facebook.com/SEEDFMalaysia/

- name: One Hope Charity
  pic: 2
  social:
    - title: webpage
      url: https://www.youtube.com/channel/UCUbr-n1cvqLvmmnKmA8JWzA
    - title: facebook
      url: https://www.facebook.com/onehopecharitywelfare/

- name: Special Hands
  pic: 3
  social:
    - title: webpage
      url: https://www.youtube.com/channel/UCUbr-n1cvqLvmmnKmA8JWzA
    - title: facebook
      url: https://www.facebook.com/acs.specialhands

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/olmcf/

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-cayman
