url: https://asvoria.github.io
baseurl: /olmcf/

# Site settings
title: Ong Lai Mun Charity Fund
email: asvoria@live.com
description: "This site is a public record of the Ong Lai Mun Charity Fund"


# Team names, titles and social links
people:
- name: SEED
  pic: seed
  position: Pertubuhan Pembangunan Kebajikan dan Persekitaran Positif Malaysia (SEED) aims to help the key affected populations (such as the homeless, people living with or affected by HIV and Transgender persons) to improve their quality of life.
  social:
    - title: globe
      url: https://seedfoundation.com.my/
    - title: facebook
      url: https://www.facebook.com/SEEDFMalaysia/

- name: One Hope Charity
  pic: one_hope
  position: One Hope Charity & Welfare is a registered non-profit organization and founded in 2002 and previously, it was known as Pertubuhan Penganut Dewi Xi Wang Dian, Bukit Mertajam, Penang. </br>
  social:
    - title: globe
      url: http://www.onehopecharity.org/
    - title: facebook
      url: https://www.facebook.com/onehopecharitywelfare/

- name: Special Hands
  pic: special_hands
  position: Special Hands is Asia Community Service, which empower people with special needs towards a more meaningful and fulfilling life in he society, especially young children and adults with intellectual disabilities.
  social:
    - title: globe
      url: http://www.asiacommunityservice.org/
    - title: facebook
      url: https://www.facebook.com/acs.specialhands

- name: Binance Charity
  pic: binance_cha
  position: Binance Charity is a Blockchain Charity Foundation that aims to transform philanthropy by developing a 100% transparent donation platform that reaches individual beneficiaries through blockchain technology.
  social:
    - title: globe
      url: https://www.binance.charity/
    - title: facebook
      url: https://www.facebook.com/BinanceBCF/
    - title: twitter
      url: https://twitter.com/BinanceBCF

- name: Give.Asia
  pic: giveasia
  position: Give.Asia is an online crowdfunding organization founded in 2009, GIVE.asia is Asia’s free fundraising platform for fundraisers to raise money for their causes.
  social:
    - title: globe
      url: https://give.asia/
    - title: facebook
      url: https://www.facebook.com/giveasia.org/

- name: MAH LAI MUN
  pic: mahlaimun
  position: Mah Lai Mun is a young woman who got bacterial infected kidney, causing multiple organ failure and needs long term continous medical care.
  social:
    - title: facebook
      url: https://www.facebook.com/galax.tom

- name: BEH SWEE CHENG
  pic: Yellow_Tulips_by_Kailanie
  position: Beh Swee Cheng is an individual who one day found a stray dog in dire need of help. She is not working under any charitable organization. Funds are collected to pay for the animal transport from the streets to the vets. 

- name: CHUN YIN LING
  pic: chunyinling
  position: Chun Yin Ling is an individual animal welfare activist who help stray dogs and cats. She is not working under any charitable organization. Funds are collected to pay for the animal transport from the streets to the vets. 

- name: MD. TAYUB ABU TALEK
  pic: balukhali
  position: Tayub is a Rohingyan reside in Malaysia. In March 2021, a fire struck the Balukhali Camp. The fund is collected and delivered to Tayub's family relatives at Balukhali to rebuild their camp.  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/olmcf/

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-cayman
